---
title: "dhs_final"
author: "Gordon Blasco"
date: "3/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(rdhs)
library(tidyverse)
library(purrr)
library(ggpubr)

set_rdhs_config(email = "gordonblasco@gmail.com",
                project = "Global Wastewater")

available <- get_available_datasets()

sanfac <- read_csv(file.path("/home/shares/ohi/git-annex/land-based/wastewater/data/interim/country_sanitation_factors.csv"))

hv205_ref <- tribble(
~hv205,      ~hv205_ref,                             ~input_type,
  10,      "FLUSH TOILET",                              "NA",
  11,      "Flush to piped sewer system",               "sewer",
  12,      "Flush to septic tank",                      "septic",
  13,      "Flush to pit latrine",                      "direct",
  14,      "Flush to somewhere else",                   "NA",
  15,      "Flush, dont know where",                    "NA",
  20,      "PIT TOILET LATRINE",                        "direct",
  21,      "Ventilated Improved Pit latrine (VIP)",     "direct",
  22,      "Pit latrine with slab",                     "direct",
  23,      "Pit latrine without slab/open pit",         "direct",
  30,      "NO FACILITY",                               "direct",
  31,      "No facility/bush/field",                    "direct",
  41,      "Composting toilet",                         "direct",
  42,      "Bucket toilet",                             "direct",
  43,      "Hanging toilet/latrine",                    "direct",
  96,      "Other",                                     "NA",
  99,      "Missing",                                   "NA"
  )  %>% 
  mutate(input_score = case_when(
    input_type == "sewer"  ~ 0.01,
    input_type == "septic" ~ 0.3,
    input_type == "direct" ~ 0.2
  ))


# get all geologic data
have_geo_data <- available   %>% 
  filter(FileType == "Geographic Data" &
         SurveyType== "DHS") %>% 
  group_by(DHS_CountryCode)  %>% 
  filter(SurveyYear == max(SurveyYear))
```

```{r}

final_df <- tibble(URBAN_RURA = NA,        
                   source = NA,            
                   sanitation_factor = NA, 
                   country = NA)[0,]

for (i in 1:nrow(have_geo_data)) {
  
  
  this_country_code <- have_geo_data$DHS_CountryCode[i]
  
  this_country_name <- have_geo_data$CountryName[i]
  
  this_survey_id <- have_geo_data$SurveyId[i]
  
  datasets <- dhs_datasets(surveyIds = this_survey_id,
                         fileFormat = "flat") 
  
  
  
  file_name <- datasets %>% 
    filter(FileType == "Household Member Recode" & SurveyId == this_survey_id) %>% 
    pull(FileName) %>% get_datasets()
  
  geo_name <- datasets %>% 
    filter(FileType == "Geographic Data" & SurveyId == this_survey_id) %>% 
    pull(FileName) %>% get_datasets()
  
  household_data <- readRDS(file_name[[1]]) %>% 
    dplyr::select(1:10, "hv025", "hv205") 
  
  geo_data <- readRDS(geo_name[[1]])@data %>% 
    dplyr::select(
      "DHSCLUST",
      "URBAN_RURA",
      "LATNUM",
      "LONGNUM"
    ) %>% 
    mutate(DHSCLUST = as.integer(DHSCLUST)) 
  
   our_sanits <- sanfac %>% 
    filter(country == this_country_name) %>% 
    dplyr::select(6:20) %>% 
    pivot_longer(everything(), names_to = "name", values_to = "value") %>% 
    filter(!str_detect(name, "_sf_septic")) %>% 
    mutate(URBAN_RURA = case_when(
      str_detect(name, "^rural") ~ "R",
      str_detect(name, "^urban") ~ "U",
      str_detect(name, "^national") ~ "Nat"
    ),
      sf_type = str_extract(name, "open|treated|septic|sf$")
    ) %>% 
    dplyr::select(-name) %>% 
    pivot_wider(id_cols = -sf_type, names_from = sf_type)
  
    
      national_level <- household_data %>%
  #rename(DHSCLUST = hv001) %>%
  dplyr::select(hv001, hv205) %>% 
  mutate(hv205 = as.numeric(hv205)) %>% 
  left_join(hv205_ref) %>% 
  filter(input_type != "NA") %>%
  mutate(hv001 = as.integer(hv001)) %>% 
  rename(DHSCLUST = hv001) %>%
  left_join(geo_data) %>% 
  summarise(sanfac_from_DHS = mean(input_score),
            DHS_septic_perc = (sum(input_type == "septic")/nrow(.)) * 100,
            DHS_open_perc = (sum(input_type == "direct")/nrow(.)) * 100,
            DHS_sewer_perc  = (sum(input_type == "sewer" )/nrow(.)) * 100) %>% 
  mutate(URBAN_RURA = "Nat")
      
      
      
      
urb_rural_level <- household_data %>%
  #rename(DHSCLUST = hv001) %>%
  dplyr::select(hv001, hv205) %>% 
  mutate(hv205 = as.numeric(hv205)) %>% 
  left_join(hv205_ref) %>% 
  filter(input_type != "NA") %>%
  mutate(hv001 = as.integer(hv001)) %>% 
  rename(DHSCLUST = hv001) %>%
  left_join(geo_data) %>% 
  group_by(URBAN_RURA) %>% 
  summarise(sanfac_from_DHS = mean(input_score),
            DHS_septic_perc = (sum(input_type == "septic")  /n()) * 100,
            DHS_open_perc =   (sum(input_type == "direct")  /n()) * 100,
            DHS_sewer_perc  = (sum(input_type == "sewer" )  /n()) * 100) %>% 
  bind_rows(national_level) %>% 
  left_join(our_sanits) %>% 
  pivot_longer(-URBAN_RURA, names_to = "source", values_to = "sanitation_factor") %>% 
  mutate(country = this_country_name)
    
  
#assign(paste0("final_df_", country_name), urb_rural_level)    



final_df <- final_df %>% 
    bind_rows(urb_rural_level)
}
```




```{r}
plotted_df <- final_df %>% 
      # filter(source == "sf" |
      #          source == "sanfac_from_DHS") %>% 
      # pivot_wider(names_from = "source", values_from = "sanitation_factor") %>% 
  drop_na() %>% 
  filter(source != "sf" &
           source != "sanfac_from_DHS") %>% 
  mutate(database = case_when(
    str_detect(source, "^DHS") ~ "DHS", 
    !str_detect(source, "^DHS") ~ "WHO"),
    
    treatment_type = case_when(
      str_detect(source, "open") ~ "open",
      str_detect(source, "septic") ~ "septic",
      str_detect(source, "sewer") ~ "sewer",
      str_detect(source, "treated") ~ "sewer"
    )
  ) %>% 
  rename(percent_pop = sanitation_factor) %>% 
  select(-source) %>% 
  #unite(source, database, treatment_type) %>% 
  pivot_wider(names_from = database, 
              values_from = percent_pop)

ggplot(plotted_df, aes(x = DHS, y = WHO))+
  geom_point()+
  geom_abline(intercept = 0, slope = 1)+
  facet_grid(treatment_type~URBAN_RURA)+
  theme_minimal()+
  ggpubr::labs_pubr()+
  labs(
    title = "Comparison of DHS and WHO's National Percent of Population Access to Treatment Type"
  ) +
  theme(legend.position = "none")
  


write_csv(plotted_df, "/home/shares/ohi/git-annex/land-based/wastewater/data/interim/DHS_WHO_treatment_compare.csv")

```

